# Generated by Django 4.1.2 on 2023-01-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_active_book_category_book_content_book_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('education', 'Education'), ('psychology', 'Psychology'), ('motivation_inspiration', 'Motivation & Inspiration')], max_length=50, null=True),
        ),
    ]
