# Generated by Django 4.1.2 on 2023-01-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_review_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='book_id_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user_id_id',
        ),
    ]
